version: '3'
services:
        flink:
                build:
                        context: flink/.
                        dockerfile: Dockerfile
                        args:
                                - FLINK_VERSION=1.6
                ports:
                        - "8081:8081"
        hdfs:
                build:
                        context: hadoop/.
                        dockerfile: Dockerfile
                        args:
                                - HADOOP_VERSION=2.8.4
                env_file: ./hadoop.env
                ports:
                        - "50070:50070"
                        - "9000:9000"
