version: '3'
services:
        jobmanager:
                build:
                        context: ./flink
                        dockerfile: Dockerfile
                        args:
                                - FLINK_VERSION=1.6
                expose:
                        - "6123"
                ports:
                        - "8081:8081"
                depends_on:
                        - namenode
                entrypoint:
                        - bash
                        - /home/flink/entrypoint.sh
                        - jobmanager
        taskmanager:
                build:
                        context: ./flink
                        dockerfile: Dockerfile
                        args:
                                - FLINK_VERSION=1.6
                expose:
                        - "6121"
                        - "6122"
                depends_on:
                        - jobmanager
                entrypoint:
                        - bash
                        - /home/flink/entrypoint.sh
                        - taskmanager
        namenode:
                env_file:
                        - ./hadoop.env
                build:
                        context: ./hadoop
                        dockerfile: Dockerfile
                        args:
                                - HADOOP_VERSION=2.8.4
                expose:
                        - "9000"
                ports:
                        - "50070:50070"
                depends_on:
                        - datanode
                entrypoint:
                        - bash
                        - /home/flink/entrypoint.sh
                        - namenode
                        - $HADOOP_DATANODE_SCALE
        datanode:
                env_file:
                        - ./hadoop.env
                build: 
                        context: ./hadoop
                        dockerfile: Dockerfile
                        args:
                                - HADOOP_VERSION=2.8.4
                entrypoint:
                        - bash
                        - /home/flink/entrypoint.sh
                        - datanode
                # Enter here the range of ports according to the number of instances.
                # The current range supports up to 26 instances.
                # Use docker-compose ps at runtime to discover the exact mappping.
                ports:
                        - "50075-50100:50075"
