FROM debian
ENV VERSION 2.8.4
SHELL ["/bin/bash", "-c"]
RUN apt-get update && apt-get install -y default-jre default-jdk ssh rsync wget sudo vim net-tools telnet rsyslog
RUN cp /usr/share/doc/rsync/examples/rsyncd.conf /etc/
RUN sed -i.bak 's/RSYNC_ENABLE=false/RSYNC_ENABLE=true/' /etc/default/rsync
RUN adduser --disabled-password hadoop
USER hadoop
WORKDIR /home/hadoop
RUN echo "" | ssh-keygen -t rsa -b 4096
RUN cat .ssh/id_rsa.pub >> .ssh/authorized_keys
RUN wget http://ftp.cc.uoc.gr/mirrors/apache/hadoop/common/hadoop-${VERSION}/hadoop-${VERSION}.tar.gz
RUN tar xzf hadoop-${VERSION}.tar.gz
RUN echo "export HADOOP_HOME=/home/hadoop/hadoop-${VERSION}" >> .bashrc
RUN echo "PATH=\"\$HADOOP_HOME/bin:\$HADOOP_HOME/sbin:$PATH\"" >> .bashrc
ADD --chown=hadoop:hadoop hadoop-env.sh hadoop-${VERSION}/etc/hadoop/
ADD --chown=hadoop:hadoop core-site.xml hadoop-${VERSION}/etc/hadoop/
ADD --chown=hadoop:hadoop hdfs-site.xml hadoop-${VERSION}/etc/hadoop/
ADD --chown=hadoop:hadoop slaves hadoop-${VERSION}/etc/hadoop/
USER root
ENTRYPOINT service ssh start && service rsync start && \
           service rsyslog start && \
           touch .ssh/known_hosts && \
           chown hadoop:hadoop .ssh/known_hosts && \
           sudo -u hadoop ssh-keyscan -t rsa 0.0.0.0 >> .ssh/known_hosts && \
           sudo -u hadoop ssh-keyscan -t rsa namenode >> .ssh/known_hosts && \
           sudo -u hadoop ssh-keyscan -t rsa datanode_1 >> .ssh/known_hosts && \
           sudo -u hadoop ssh-keyscan -t rsa datanode_2 >> .ssh/known_hosts && \
           tail -f /dev/null
